name: Tests

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner:
        required: true
        type: string

jobs:
  define-matrix:
    name: Define spread matrix
    runs-on: ubuntu-latest
    outputs:
      suites: ${{ steps.suites.outputs.suites }}
      empty: ${{ steps.suites.outputs.empty }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install spread
        run: go install github.com/canonical/spread/cmd/spread@latest

      - name: Generate matrix list
        id: suites
        run: |
          list="$(spread -list github-ci 2>/dev/null | sed "s|github-ci:ubuntu-24.04:tests/||g" | jq -r -ncR '[inputs | select(length>0)]')"
          if [[ -z "$list" || "$list" == "[]" ]]; then
            echo "No spread suites defined."
            echo "empty=true" >> "$GITHUB_OUTPUT"
            echo "suites=[]" >> "$GITHUB_OUTPUT"
          else
            echo "empty=false" >> "$GITHUB_OUTPUT"
            echo "suites=$list" >> "$GITHUB_OUTPUT"
          fi

  spread-test:
    name: Spread (${{ matrix.suite }})
    runs-on: ${{ inputs.runner }}
    needs:
      - define-matrix
    if: needs.define-matrix.outputs.empty == 'false'
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJSON(needs.define-matrix.outputs.suites) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          architecture: ${{ inputs.arch }}

      - name: Install spread
        run: go install github.com/canonical/spread/cmd/spread@latest

      - name: Run integration tests
        env:
          SUITE: ${{ matrix.suite }}
        run: spread -v "github-ci:ubuntu-24.04:tests/${SUITE}"
